Repository nimblehq/git-template, pull requests merged in 2022-07, with the labels that each got.

#27 Improve the description in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: priority : high, type : chore

#28 Remove extra character in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type : bug

#30 [#29] Update the About section in the REAMDME.md file
  README.md
Labels: type : chore
